src/components/picker/color.jsx
=> color변경 기능 추가

src/assets/scss/common/_images.scss, src/components/picker/color.jsx, src/components/popup/Contents/WriteBox.jsx, src/components/popup/Navigation.jsx, src/utils/Common.js
- 1. 드랍다운, 컬러피커 열린 상태에서 클릭할 경우 닫히도록 수정
- 2. 글쓰기 팝업에서 선택된 속성값 css 수정. 테두리도 파란색이 되도록.
=> [#10062] 팝업 수정.

src/components/picker/ColorSwatches.jsx
[#10122](https://oss.navercorp.com/entry/Entry/issues/10122) 처리하면서 추가 처리
- 워닝 메세지 관련 수정.(key 세팅)
=> react key관련 워닝 제거

src/utils/Common.js
https://oss.navercorp.com/entry/Entry/issues/10138
=> [#10138] 글상자 폰트 추가.

src/components/picker/ColorSlider.jsx, src/components/picker/color.jsx
[#10122](https://oss.navercorp.com/entry/Entry/issues/10122)
추가 PR입니다.
더불어
[#9967](https://oss.navercorp.com/entry/Entry/issues/9967) 이슈도 함께 처리하였습니다.
=> #9967, #10122 이슈 처리

package.json, src/assets/scss/widget/BackPack.scss, src/components/widget/BackPack.jsx, yarn.lock
[#8410](https://oss.navercorp.com/entry/Entry/issues/8410)이슈 처리
1. 터치 디바이스에서 정상 작동 하도록 수정.
=> 백팩 터치 환경 대응

rollup.config.js
[#10236](https://oss.navercorp.com/entry/Entry/pull/10236)
entrylabs/entryjs#1266
머지할때 같이 머지
=> tool bower 빌드용

src/components/popup/Contents/FileUpload.jsx
1. FileUpload.jsx
- ws -> 오브젝트 추가하기 -> 파일 올리기 오타자(;) 삭제
=> 업로드 오타자 수정

src/components/popup/Contents/FileUpload.jsx
필요없는 로직 제거.  ( beforeUpload는 항상 새로 들어와서 이전것과 길이를 비교할 필요가 없음..)
=> [#10523] 이슈 처리.

src/assets/entryline/scss/popup.scss, src/components/popup/Contents/Projects.jsx, src/components/popup/Navigation.jsx
- 프로젝트 팝업일 경우 카테고리가 한글이여서 키를 보내도록 수정.
- 디폴트 아바타 이미지를 받을 수 있도록 수정.
=> [#line_332] 프로젝트 팝업 적용

src/constants/index.js
https://oss.navercorp.com/entry/Entry/issues/10839
=> 모양/오브젝트 인터페이스 카테고리에 하위분류 추가

src/components/popup/Contents/WriteBox.jsx, src/components/widget/dropdown.jsx, src/constants/index.js
https://oss.navercorp.com/entry/Entry/issues/10736
=> [#10736]  스타일 변경 가능하도록 수정.

src/assets/entryline/scss/popup.scss
1. 작품불러오기 팝업 드롭다운 사이즈 변경
- 텍스트 길이관련 수정 ( 130px -> 150px)
https://oss.navercorp.com/entryline/lineentry/issues/410
=> entryline/Issue/410 드롭다운 관련 스타일 수정

src/assets/entryline/scss/popup.scss
https://oss.navercorp.com/entryline/lineentry/issues/294
=> [#294] font bold

src/components/popup/Contents/Projects/Item.jsx
Fix invalid(undefined) avatar image path.
It seems to be changed for Line Entry.
=> issue #11227 make avatar image url for Entry

src/components/ledPicker/ledPicker.jsx, src/components/popup/Contents/Select/BigICON/index.jsx, src/components/popup/index.jsx, src/constants/index.js
https://github.com/entrylabs/entryjs/pull/1583
https://oss.navercorp.com/entry/Entry/issues/10910
=> [#10910] 오디오 감지 블록

src/assets/entry/scss/popup.scss, src/components/popup/Contents/Select/BigICON/Item.jsx
https://github.com/entrylabs/entryjs/pull/1590
=> sponser Text 영역 추가

src/assets/entry/scss/popup.scss, src/components/ai_layout/DataDetail.jsx
@prisml 님 요청하신대로 범례 톱니바퀴 아이콘을 dom 엘리먼트로 변경하였습니다.
PR 확인 부탁 드리겠습니다.
=> WS Ai - 차트 레이아웃 범례 :after 클래스 -> dom 엘리먼트로 변경

src/assets/entry/scss/popup.scss, src/components/ai_layout/DataDetail.jsx
영덕님이 요청해주신 scroll 세로 가변 대응을 하여 PR 전달 드립니다. 확인 부탁 드리겠습니다.
=> WS - Ai 레이어 차트 스몰리스트 overflow: scroll 가변 대응

src/assets/entry/scss/popup.scss, src/components/ai_layout/DataDetail.jsx
@prisml 님 우측 상단 범례쪽에 말풍선 툴팁은 5개 이상일때 스크롤 발생, 
범례 표시는 202px  이상일때 스크롤이 발생할 수 있도록 추가 하였습니다.
디자이너님에게 확인 받았습니다. 스크롤이 추가되면서 일부 css 가 추가 / 수정되었으니 참고 부탁드리겠습니다.
=> WS- Ai 범례 레이어 스크롤 영역 추가

src/assets/entry/scss/popup.scss, src/components/popup/Contents/Draw.jsx
[#11275](https://oss.navercorp.com/entry/Entry/issues/11275)
=> 이슈 11275 처리

src/components/editor/dataAnalytics/Constants.js, src/components/widget/Chart.jsx
https://oss.navercorp.com/entry/Entry/issues/11432
=> [Chart] chart 표현 불가능 처리 조건 흐름 수정

src/assets/entry/scss/popup.scss, src/components/editor/dataAnalytics/DataAnalyticsEditor.jsx
- react portal로 body 가장 하위로 이동
https://oss.navercorp.com/entry/Entry/issues/11430
=> [DataAnalyticsEditor] ie에서 전체화면 틀어짐 문제 수정

src/assets/entry/scss/popup.scss
Reverts entrylabs/entry-tool#137
=> Revert "Feature/datavisualize"

src/components/editor/dataAnalytics/reducer/DataAnalyticsReducer.js
- 차틍 생성시에 이름 추가
https://oss.navercorp.com/entry/Entry/issues/11439
=> [DataAnalyticsReducer] 차트 보기 화면에서 차트 제목 비정상 노출

src/components/editor/dataAnalytics/chart/ChartLayout.jsx, src/components/widget/Chart.jsx
https://oss.navercorp.com/entry/Entry/issues/11437
=> [ChartLayout] 아이콘 삭제

src/actions/editor.js, src/components/editor/dataAnalytics/DataAnalytics.jsx, src/components/editor/dataAnalytics/DataAnalyticsContainer.jsx, src/components/editor/dataAnalytics/context/DataAnalyticsContext.js, src/components/editor/dataAnalytics/reducer/DataAnalyticsReducer.js, src/middleware/emit.js
https://oss.navercorp.com/entry/Entry/issues/11433
=> [DataAnalytics] DataAnalytics 편집 이벤트 발생 추가

src/components/widget/Table.jsx
- event 내의 clientX, clientY 속성 사용
https://oss.navercorp.com/entry/Entry/issues/11447
=> [Table] IE 환경에서, 테이블 행/열에 마우스 우클릭 실행되지 않음

src/components/widget/Table.jsx
- setTable 위치 수정
- 행 한개 이하 삭제 시도시 토스트 추가
https://oss.navercorp.com/entry/Entry/issues/11448
=> [Table] 행 삭제하기 기능이 동작하지 않습니다

src/components/widget/Table.jsx
- colIndex -1 인 영역 기능 수행 막음
https://oss.navercorp.com/entry/Entry/issues/11446
=> [Table] No 영역 더블 클릭 시, 열 이름 수정 기능이 실행

src/components/editor/dataAnalytics/context/DataAnalyticsContext.js
https://oss.navercorp.com/entry/Entry/issues/11475
=> [DataAnalyticsContext] 에러 방어코드 추가

src/components/editor/dataAnalytics/DataAnalytics.jsx, src/components/editor/dataAnalytics/TableEditor.jsx, src/components/widget/Table.jsx
- 얕은복사로 저장하지 않아도 원본이 변경되는 부분 수정
https://oss.navercorp.com/entry/Entry/issues/11474
=> [Table] 테이블 편집 후 변경이벤트 발생

src/assets/entry/scss/popup.scss
[#11535](https://oss.navercorp.com/entry/Entry/issues/11535) 드롭다운 디자인 처리
=> 드롭다운 호버 문제 해결

src/assets/entry/scss/progress.scss, src/components/widget/modalProgress.jsx
로딩 팝업 관련하여서 minimized 인 케이스를 추가하였습니다. mode: "minimize" 인 경우 전체 화면이 아닌 작품 실행창에 한하여서 팝업이 뜨도록 하였습니다. 현재 Loading 외에는 다른 팝업이 필요하다고 생각되지 않아서 loading의 경우에 대하여만 추가하였습니다.
=> [Issue/11561-2] ws minimize 케이스 추가

src/assets/entry/scss/progress.scss, src/components/widget/modalProgress.jsx, src/stories/index.js
https://github.com/entrylabs/entry-tool/pull/161
https://github.com/entrylabs/entryjs/pull/1694
[#11578](https://oss.navercorp.com/entry/Entry/pull/11578)
=> [전체화면 로딩팝업] minimize 케이스 추가

src/assets/entry/scss/customScroll.scss, src/assets/entryline/scss/customScroll.scss, src/components/common/customScroll.jsx
[#311](https://oss.navercorp.com/entryline/lineentry/issues/311)
=> 라인 이슈 311 처리

package.json, src/components/widget/Table.jsx, yarn.lock
https://oss.navercorp.com/entry/Entry/issues/11581
- 라이브러리 버전 갱신
- tab의 기능과 rerender로 인한 editing finish 중복
- editing start에 이전 값을 저장하여 문제 해결
=> [Table] Tab키 입력 시, 테이블 편집 화면이 비정상적 노출

src/components/editor/dataAnalytics/TableEditor.jsx, src/components/editor/dataAnalytics/context/DataAnalyticsContext.js, src/components/editor/dataAnalytics/reducer/DataAnalyticsReducer.js, src/components/widget/Table.jsx, src/utils/Common.js
- gridRef를 context로 옮김
https://oss.navercorp.com/entry/Entry/issues/11579
=> [DataAnalytics] 탭이 이동될때 grid data 적용

src/components/popup/Contents/Navigation/index.jsx
https://oss.navercorp.com/entryline/lineentry/issues/495
=> [line/issue/495] searchBox 에러 수정

src/assets/entry/scss/popup.scss, src/components/widget/modalChart.jsx
https://oss.navercorp.com/entry/Entry/issues/11572
1. workspace 이외에 차트모달 오픈시 스크롤 숨김처리 되도록 수정
2.dimm 포지션 스타일 수정
=> Issue/11572 차트모달 스크롤 기능 수정

src/components/editor/dataAnalytics/TableEditor.jsx, src/components/editor/dataAnalytics/chart/ChartLayout.jsx, src/components/editor/dataAnalytics/reducer/DataAnalyticsReducer.js, src/components/widget/Table.jsx
- 테이블에서 추가/삭제한 인덱스가 이미 지정된 차트에 적용되지 않던 문제
- reducer에 로직 추가
https://oss.navercorp.com/entry/Entry/issues/11616
=> [DataAnalyticsReducer] column 추가 삭제 동작 사이드 이팩트 처리

src/components/widget/modalProgress.jsx
https://oss.navercorp.com/entry/Entry/issues/11398#issuecomment-4225493
entry-js: https://github.com/entrylabs/entryjs/pull/1720
Entry:
=> 로딩 팝업 문구 멀티라인 적용

src/assets/entry/scss/popup.scss
세로형 범례 첫번째 / 두번째 셀 말줄임 추가 및 max-width 설정
=> 세로형 범례 말줄임 추가 max-width 값 재정의

src/components/widget/modalChart.jsx
=> [modalChart] props 기존방식으로 수정

src/assets/entry/scss/popup.scss, src/assets/entry/scss/scroll.scss, src/components/ledPicker/ledPicker.jsx, src/components/widget/dropdownExtra.jsx, src/components/widget/dropdownExtraContainer.jsx, src/index.jsx, src/stories/index.js, src/wrapper2.jsx
[#11691](https://oss.navercorp.com/entry/Entry/issues/11691)
=> [WIP]Feature/dropdown extra

src/assets/entry/scss/popup.scss, src/components/widget/dropdownExtra.jsx
https://app.zeplin.io/project/5b834f7f278d63626f2a01d4/screen/5e9e85079d41517b325072db
https://oss.navercorp.com/entry/Entry/issues/11691#issuecomment-4327543
=> [dropdownExtra] css fix 5 col -> 4 col

src/components/widget/Chart.jsx
=> [Chart] 원형 차트에서 마우스 오버 레이블, 값, 퍼센트를 모두 표시

src/components/editor/dataAnalytics/TableEditor.jsx, src/components/editor/dataAnalytics/reducer/DataAnalyticsReducer.js, src/components/widget/Table.jsx
- context state와 컴포넌트 state 차이로 발생하는 문제
- column 추가, 삭제와 같은 방식으로 처리
- hotfix 처리
- 추후 전체적인 구조 수정이 필요함
- todo: render 부분에 grid 안쓰도록 수정해야함
=> [Table] row 추가 삭제를 props로 받아 사용

src/components/popup/Contents/FileUpload/index.jsx, src/components/popup/Contents/Select/BigICON/Item.jsx, src/components/popup/Contents/Select/SideBar/Item.jsx, src/components/popup/Contents/Select/SideBar/Selected.jsx, src/components/popup/Contents/Select/SideBar/index.jsx, src/selectors/index.js
=> [Popup] select 판별 id 추가

src/components/editor/dataAnalytics/chart/HorizontalLegend.jsx, src/components/widget/modalChart.jsx
https://oss.navercorp.com/entry/Entry/issues/12169
=> [HorizontalLegend] theme 적용

src/assets/entry/scss/lecture-popup.scss, src/assets/entry/scss/popup.scss
https://oss.navercorp.com/entry/Entry/issues/12169
- lecture popup z-index가 9999이므로 10000으로 수정
=> [popup] edit z-index

src/assets/entry/scss/components/_TableAdd.scss, src/assets/entry/scss/components/_TableSummary.scss
https://oss.navercorp.com/entry/Entry/issues/12217?email_source=notifications&email_token=AAACGJPGV3ZBZTTA72YKDO3SXPJKBA5CNFSM4ABP4QQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOABJUJHY
https://oss.navercorp.com/entry/Entry/issues/12217?email_source=notifications&email_token=AAAA456AU4BIGPE2LICTMCTSV3SJBA5CNFSM4ABP4QQ2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOAFRGUKI#issuecomment-5457055
위 두가지 부분을 대응하여 PR 드립니다.
=> 테이블 관련 디자인 검수사항 대응

src/assets/entry/images/IconButtonMinus.svg, src/assets/entry/images/IconButtonPlus.svg, src/assets/entry/images/icon_chart_sel05_off.svg, src/assets/entry/images/icon_chart_sel05_on.svg, src/assets/entry/scss/common/_tooltip.scss, src/assets/entry/scss/components/_TableChart.scss, src/components/ai_layout/TableChart.jsx, src/stories/index.js
데이터 차트 - 히스토그램 그래프 차트를 추가하여 PR 드립니다. 
개발 적용시 참고 부탁 드리겠습니다.
=> 데이터 차트 - 히스토그램 추가

src/components/editor/dataAnalytics/chart/ChartLayout.jsx, src/components/widget/Chart.jsx, src/utils/dataAnalytics.js
=> [#12328] 데이터 테이블 열이 하나일 때 히스토그램 차트를 그릴 수 없음

src/components/widget/Chart.jsx
- 소수점 2째 자리까지 표현을 하여서 2째자리 넘어서 반올림 한값으로 비교
=> [#12333] js 소숫점 계산 문제로 인한 처리

src/components/popup/Contents/FileDragUpload/index.jsx, src/components/popup/Contents/FileUpload/index.jsx
[#2231](https://oss.navercorp.com/entry/entry2/issues/2231)
=> #2231 업로드완료 체크 관련 수정

src/assets/entry/scss/progress.scss
[#2902](https://oss.navercorp.com/entry/entry2/issues/2902)
=> #2902 css 수정

package.json, src/assets/entry/scss/popup.scss, src/components/popup/Contents/Projects/index.jsx, src/components/popup/index.jsx, src/constants/index.js, yarn.lock
[#2990](https://oss.navercorp.com/entry/entry2/issues/2990)
=> 이슈 2990 처리

src/components/popup/Contents/FileUpload/index.jsx
[#3503](https://oss.navercorp.com/entry/entry2/issues/3503)
=> 사운드 파일 업로드 팝업 누락된 class 추가

src/components/widget/dropdown.jsx
[#2094](https://oss.navercorp.com/entry/entry2/issues/2094)
=> [dropdown] disabled 옵션을 받았을때 처리

src/components/editor/dataAnalytics/SaveConfirm.jsx, src/components/editor/dataAnalytics/Tab.jsx, src/components/widget/Table.jsx
=> entry-modal css제거.

src/assets/entry/scss/popup.scss
=> feat: 하드웨어 웹연결 팝업 고객센터 스타일 변경

src/components/popup/Contents/Navigation/SearchBox.jsx, src/components/popup/Contents/Projects/index.jsx
[#4685](https://oss.navercorp.com/entry/entry2/issues/4685)
=> [#4685] 작품 불러오기 팝업 검색 필터 값 최신화

src/components/editor/dataAnalytics/summary/Table.jsx
[#5146](https://oss.navercorp.com/entry/entry2/issues/5146)
=> [table] 테이블의 행의 개수가 1개 작은 수로 처리됨

src/components/popup/Contents/FileUpload/UploadInput.jsx
- input 초기화
[#5176](https://oss.navercorp.com/entry/entry2/issues/5176)
=> [upload] 허용되지 않는 소리 파일을 2회 업로드 시도 시에 얼럿 노출 되지 않음

webpack.config.js
[#4986](https://oss.navercorp.com/entry/entry2/issues/4986)
=> [#4986] IE11 대응, bable-loader 수정

src/components/widget/modalTable.jsx, src/components/widget/modalTableContainer.jsx, src/index.jsx
[#5323](https://oss.navercorp.com/entry/entry2/issues/5323)
=> [#5323] 테이블의 현재 상태를 저장하기, 테이블 창 열기 블록을 추가

babel.config.js
- 5352관련하여 ws속성 > 리스트 > 불러오기,내보내기 팝업에서 React is not defined 오류가 발생하여 추가
=> fix: 바벨 react 설정 추가

src/assets/entry/scss/popup.scss, src/components/popup/Contents/FileUpload/Item.jsx, src/components/popup/Contents/Navigation/SearchOption.jsx, src/components/popup/Contents/Select/SideBar/Item.jsx, src/components/popup/Contents/Select/SideBar/index.jsx, src/components/popup/Contents/Select/index.jsx, src/components/popup/Contents/includes/PopupList/TablePopupList.jsx, src/components/popup/Contents/includes/SelectItem/TableSelectItem.jsx, src/components/popup/index.jsx, src/components/widget/dropdownContainer.jsx
[#5294](https://oss.navercorp.com/entry/entry2/issues/5294)
=> [4.18.0][#5294] 다른 유형의 데이터셋(결측치, 이상치 포함 등)을 선택하는 기능을 추가

src/assets/entry/scss/popup.scss, src/assets/entry/scss/tree.scss, src/components/widget/Tree.jsx, src/components/widget/TreeNodeContainer.jsx, src/index.jsx, src/stories/index.js
[#5068](https://oss.navercorp.com/entry/entry2/issues/5068)
=> 이진트리 팝업 추가

src/assets/entry/scss/components/_TableChart.scss, src/components/ai_layout/TableChart.jsx
[#5209](https://oss.navercorp.com/entry/entry2/issues/5209)
=> [#5209] [WS] 데이터 분석에 새로운 기능(산점도 행렬, 차트 크게 보기 등)을 추가 - 산점도 행렬 그래프 축 레이블 마크업

src/assets/entry/scss/common/_tooltip.scss, src/assets/entry/scss/components/_TableChart.scss, src/assets/entry/scss/components/_TableSummary.scss, src/assets/entry/scss/popup.scss, src/assets/entry/scss/widget/insight.css, src/components/editor/dataAnalytics/chart/ChartLayout.jsx, src/components/editor/dataAnalytics/chart/properties/degree/Boundary.jsx, src/components/editor/dataAnalytics/chart/properties/degree/Range.jsx, src/components/widget/Chart/Bar.jsx, src/components/widget/Chart/Plotly.jsx, src/components/widget/modalChart.jsx, src/components/widget/modalTable.jsx
@jooheemoon 
[#5209](https://oss.navercorp.com/entry/entry2/issues/5209) 이슈에 올라온 수정사항 반영 입니다.
=> 디자인 수정 요청 사항 반영

src/assets/entry/scss/components/_TableChart.scss, src/components/editor/dataAnalytics/chart/ChartLayout.jsx
@kimorkim 
https://oss.navercorp.com/entry/entry2/issues/5209#issuecomment-9287420 관련 수정 내역입니다.
어제 수정해주신 내역 중, `margin60` 때문에 생기는 이슈라서 제거했습니다.
https://github.com/entrylabs/entry-tool/commit/bb9d3a0346332a41bc526277acede8b8da071393#diff-f8c463dec7c8b15cafec854b0c58f537f2e23ae457d702f17d1f7b22e9f526d4R267
해당 클래스가 필요한 이유가 있다면 코멘트 주시면 추가로 확인해보겠습니다.~
=> [#5209] [WS] 데이터 분석에 새로운 기능(산점도 행렬, 차트 크게 보기 등)을 추가 - 디자인 검수 반영

src/components/popup/Contents/FileUpload/UploadInput.jsx
[#5758](https://oss.navercorp.com/entry/entry2/issues/5758)
=> 10mb -> 5mb

src/components/popup/Contents/FileUpload/UploadInput.jsx
[#5758](https://oss.navercorp.com/entry/entry2/issues/5758)
=> 이슈 5758 처리

src/assets/entry/scss/popup.scss, src/components/popup/Contents/Select/CardCategoryView/Item.jsx, src/components/popup/Contents/Select/CardCategoryView/index.jsx
[#6736](https://oss.navercorp.com/entry/entry2/issues/6736)
=> 6736 추가 이슈 처리

package.json, pnpm-lock.yaml, src/components/popup/Contents/includes/SelectItem/SoundSelectItem.jsx
* play, stop할때 item정보 보내도록 추가
* add pnpm-locck
---------
=> Issue/7630 (#424)

src/assets/entry/scss/list.scss
-todo : box-sizing이 팝업 리스트에만 안먹히고 있음
=> [#8148] 스터디, 발견WS에서 레이아웃 깨짐 수정

src/assets/entry/scss/popup.scss, src/components/popup/Contents/Select/BigICON/Item.jsx, src/components/popup/Contents/Select/BigICON/index.jsx
https://oss.navercorp.com/entry/entry2/issues/7700
=> [하드웨어] 블록메뉴, 모달팝업 UX 변경

src/assets/entry/scss/common/_tooltip.scss, src/components/ledPicker/ledPicker.jsx
https://oss.navercorp.com/entry/entry2/issues/8917
=> [#8917] ledPicker 사이즈변경 대응
